"""Research agent for gathering information from codebases and external sources."""
from __future__ import annotations

import re
from dataclasses import dataclass, field

__all__ = ["Finding", "ResearchPlan", "Researcher", "Source"]


@dataclass
class Source:
    """A single information source discovered during research.

    Attributes:
        name: Human-readable source identifier (e.g. filename, page title).
        content: The raw text content of the source.
        url: Optional URL if the source is web-based.
        relevance: Relevance score in ``[0, 1]``.  Defaults to 1.0.
    """

    name: str
    content: str
    url: str = ""
    relevance: float = 1.0


@dataclass
class Finding:
    """A discrete research finding backed by one or more sources.

    Attributes:
        title: Short, descriptive title for the finding.
        summary: Prose summary of what was found.
        sources: Sources that support this finding.
        confidence: Confidence score in ``[0, 1]``.  Defaults to 0.0.
        tags: Free-form tags for categorisation.
    """

    title: str
    summary: str
    sources: list[Source]
    confidence: float = 0.0
    tags: list[str] = field(default_factory=list)


@dataclass
class ResearchPlan:
    """A structured plan for answering a research question.

    Attributes:
        question: The top-level research question.
        sub_questions: The question decomposed into smaller, answerable parts.
        search_terms: Keywords and phrases to search for.
    """

    question: str
    sub_questions: list[str]
    search_terms: list[str]


class Researcher:
    """Gathers information from codebases and synthesises findings.

    Args:
        max_sources: Maximum number of sources to return from a single search.

    Example::

        researcher = Researcher(max_sources=5)
        plan = researcher.plan("How does authentication work?")
        sources = researcher.search_codebase(plan.search_terms[0], files)
        researcher.add_finding(Finding(
            title="Auth flow",
            summary="Uses JWT tokens",
            sources=sources,
        ))
        report = researcher.synthesize(researcher.findings)
    """

    def __init__(self, max_sources: int = 10) -> None:
        self._max_sources = max_sources
        self._findings: list[Finding] = []

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def plan(self, question: str) -> ResearchPlan:
        """Decompose a research question into sub-questions and search terms.

        Uses simple keyword extraction to derive search terms from the
        question.  Sub-questions are generated by splitting on common
        interrogative patterns and by producing aspect-oriented variants.

        Args:
            question: The research question to decompose.

        Returns:
            A ``ResearchPlan`` with sub-questions and search terms.
        """
        search_terms = self._extract_search_terms(question)
        sub_questions = self._generate_sub_questions(question)
        return ResearchPlan(
            question=question,
            sub_questions=sub_questions,
            search_terms=search_terms,
        )

    def search_codebase(
        self,
        query: str,
        files: dict[str, str],
    ) -> list[Source]:
        """Search a set of files for content matching *query*.

        Each file whose content contains *query* (case-insensitive) is
        returned as a ``Source``.  Results are sorted by relevance
        (number of occurrences) and capped at ``max_sources``.

        Args:
            query: Search string (matched case-insensitively).
            files: Mapping of ``{filename: file_content}``.

        Returns:
            A list of ``Source`` objects, at most ``max_sources`` long.
        """
        sources: list[Source] = []
        query_lower = query.lower()
        for name, content in files.items():
            count = content.lower().count(query_lower)
            if count > 0:
                sources.append(
                    Source(
                        name=name,
                        content=content,
                        relevance=min(1.0, count / 10.0),
                    )
                )
        # Sort by relevance descending, then by name for stability.
        sources.sort(key=lambda s: (-s.relevance, s.name))
        return sources[: self._max_sources]

    def add_finding(self, finding: Finding) -> None:
        """Record a new finding.

        Args:
            finding: The ``Finding`` to add.
        """
        self._findings.append(finding)

    @property
    def findings(self) -> list[Finding]:
        """Return all recorded findings."""
        return list(self._findings)

    def synthesize(self, findings: list[Finding]) -> str:
        """Combine a list of findings into a prose summary.

        Each finding is rendered as a titled section.  If *findings* is
        empty the string ``"No findings to synthesize."`` is returned.

        Args:
            findings: Findings to synthesise.

        Returns:
            A plain-text summary string.
        """
        if not findings:
            return "No findings to synthesize."

        sections: list[str] = []
        for finding in findings:
            source_names = ", ".join(s.name for s in finding.sources) or "none"
            section = (
                f"## {finding.title}\n"
                f"{finding.summary}\n"
                f"Sources: {source_names}\n"
                f"Confidence: {finding.confidence:.1f}"
            )
            sections.append(section)
        return "\n\n".join(sections)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    _STOP_WORDS: set[str] = {
        "a", "an", "the", "is", "are", "was", "were", "be", "been",
        "being", "have", "has", "had", "do", "does", "did", "will",
        "would", "could", "should", "may", "might", "shall", "can",
        "it", "its", "of", "in", "to", "for", "with", "on", "at",
        "by", "from", "as", "into", "about", "between", "through",
        "and", "or", "but", "not", "no", "if", "then", "than", "so",
        "what", "how", "where", "when", "which", "who", "whom",
        "this", "that", "these", "those", "i", "we", "you", "they",
        "my", "our", "your", "their", "me", "us", "him", "her",
    }

    def _extract_search_terms(self, question: str) -> list[str]:
        """Extract meaningful keywords from *question*.

        Returns:
            Deduplicated list of lowercase keywords with stop-words removed.
        """
        # Strip punctuation, lowercase, split.
        tokens = re.findall(r"[a-zA-Z0-9_]+", question.lower())
        seen: set[str] = set()
        terms: list[str] = []
        for token in tokens:
            if token not in self._STOP_WORDS and token not in seen:
                seen.add(token)
                terms.append(token)
        return terms

    def _generate_sub_questions(self, question: str) -> list[str]:
        """Produce aspect-oriented sub-questions from *question*.

        Returns:
            A list of sub-questions derived from the original question.
        """
        terms = self._extract_search_terms(question)
        sub_questions: list[str] = []
        if terms:
            sub_questions.append(f"What is {terms[0]}?")
        if len(terms) >= 2:
            sub_questions.append(
                f"How does {terms[0]} relate to {terms[1]}?"
            )
        if len(terms) >= 3:
            sub_questions.append(
                f"What role does {terms[2]} play?"
            )
        return sub_questions
